services:
  swquery-db:
    image: postgres:12
    environment:
      POSTGRES_DB: swquery
      POSTGRES_USER: swquery
      POSTGRES_PASSWORD: swquery
    ports:
      - "5432:5432"
    volumes:
      - "../server/database/init.sql:/docker-entrypoint-initdb.d/init.sql"

  # server:
  #   build:
  #     context: ../server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5500:5500"
  #   depends_on:
  #     - swquery-db
  #   env_file:
  #     - ../.env
  # agent:
  #   build:
  #     context: ../ai-agent
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - server
  #   env_file:
  #     - ../ai-agent/.env

volumes:
  swquery-db-data:
